# Generated by Django 5.1.7 on 2025-03-15 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_initial'),
        ('parking', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facedetection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseplatedetection',
            name='parking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_plate_detections', to='parking.parkingsession'),
        ),
        migrations.AddField(
            model_name='licenseplatedetection',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_plate_detections', to='vehicles.vehicle'),
        ),
    ]
