# Generated by Django 5.1.7 on 2025-03-13 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پارکینگ')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('parking_type', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='public', max_length=10, verbose_name='نوع پارکینگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پارکینگ',
                'verbose_name_plural': 'پارکینگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.TextField(verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('total_capacity', models.PositiveIntegerField(default=0, verbose_name='total capacity')),
                ('current_occupancy', models.PositiveIntegerField(default=0, verbose_name='current occupancy')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='hourly rate')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='daily rate')),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monthly rate')),
                ('has_cctv', models.BooleanField(default=False, verbose_name='has CCTV')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='has elevator')),
                ('has_electric_charger', models.BooleanField(default=False, verbose_name='has electric charger')),
                ('indoor', models.BooleanField(default=False, verbose_name='indoor')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='opening time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='closing time')),
                ('is_24h', models.BooleanField(default=False, verbose_name='is 24 hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parking lot',
                'verbose_name_plural': 'parking lots',
            },
        ),
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تعرفه')),
                ('hourly_rate', models.PositiveIntegerField(verbose_name='نرخ ساعتی (ریال)')),
                ('daily_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='نرخ روزانه (ریال)')),
                ('monthly_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='نرخ ماهانه (ریال)')),
                ('vehicle_type', models.CharField(choices=[('car', 'سواری'), ('motorcycle', 'موتور سیکلت'), ('suv', 'شاسی بلند'), ('truck', 'کامیون')], default='car', max_length=15, verbose_name='نوع خودرو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع اعتبار')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اعتبار')),
            ],
            options={
                'verbose_name': 'تعرفه پارکینگ',
                'verbose_name_plural': 'تعرفه\u200cهای پارکینگ',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateTimeField(verbose_name='زمان شروع رزرو')),
                ('reservation_end', models.DateTimeField(verbose_name='زمان پایان رزرو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('checked_in', 'ورود انجام شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'رزرو پارکینگ',
                'verbose_name_plural': 'رزروهای پارکینگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='entry time')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='exit time')),
                ('entry_image', models.ImageField(blank=True, null=True, upload_to='parking_sessions/entry/', verbose_name='entry image')),
                ('exit_image', models.ImageField(blank=True, null=True, upload_to='parking_sessions/exit/', verbose_name='exit image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=10, verbose_name='status')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount due')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parking session',
                'verbose_name_plural': 'parking sessions',
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, verbose_name='شماره جایگاه')),
                ('status', models.CharField(choices=[('available', 'در دسترس'), ('occupied', 'اشغال شده'), ('reserved', 'رزرو شده'), ('unavailable', 'غیر قابل دسترس')], default='available', max_length=15, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'جایگاه پارک',
                'verbose_name_plural': 'جایگاه\u200cهای پارک',
            },
        ),
        migrations.CreateModel(
            name='ParkingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('semiannual', 'شش ماهه'), ('annual', 'سالانه')], default='monthly', max_length=15, verbose_name='نوع اشتراک')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('amount_paid', models.PositiveIntegerField(verbose_name='مبلغ پرداخت شده (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اشتراک پارکینگ',
                'verbose_name_plural': 'اشتراک\u200cهای پارکینگ',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='capacity')),
                ('current_occupancy', models.PositiveIntegerField(default=0, verbose_name='current occupancy')),
                ('zone_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('disabled', 'Disabled')], default='regular', max_length=10, verbose_name='zone type')),
                ('floor', models.IntegerField(default=0, verbose_name='floor')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='price multiplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parking zone',
                'verbose_name_plural': 'parking zones',
            },
        ),
    ]
