# Generated by Django 5.1.7 on 2025-03-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        ('payments', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parkings', to=settings.AUTH_USER_MODEL, verbose_name='مدیر پارکینگ'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parking_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingrate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='parkingrate',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rates', to='parking.parkinglocation', verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkinglocation', verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicles.vehicle', verbose_name='خودرو'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions_vehicles', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='parking.parkinglocation', verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking.parkingslot'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='parking.parkingslot', verbose_name='جایگاه پارک'),
        ),
        migrations.AddField(
            model_name='parkingsubscription',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='parking.parkinglocation', verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='parkingsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='parkingsubscription',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vehicles.vehicle', verbose_name='خودرو'),
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parking.parkinglot'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('parking', 'slot_number')},
        ),
    ]
