# Generated by Django 5.1.7 on 2025-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ پرداختی'),
        ),
    ]
