# Generated by Django 5.1.7 on 2025-03-15 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='license plate')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('van', 'Van'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle')], default='sedan', max_length=15, verbose_name='vehicle type')),
                ('make', models.CharField(max_length=50, verbose_name='make')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='color')),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='vehicle image')),
                ('license_plate_image', models.ImageField(blank=True, null=True, upload_to='license_plates/', verbose_name='license plate image')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='verification date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='price multiplier')),
                ('allowed_vehicle_types', models.JSONField(default=list, verbose_name='allowed vehicle types')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehicle category',
                'verbose_name_plural': 'vehicle categories',
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(verbose_name='زمان ورود')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='active', max_length=15, verbose_name='وضعیت')),
                ('calculated_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ محاسبه شده (ریال)')),
                ('calculated_duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان محاسبه شده (ساعت)')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='parking.parkinglocation', verbose_name='پارکینگ')),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to='parking.parkingslot', verbose_name='جایگاه پارک')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to='parking.parkingreservation', verbose_name='رزرو')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to='parking.parkingsubscription', verbose_name='اشتراک')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='vehicles.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'جلسه پارک',
                'verbose_name_plural': 'جلسات پارک',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('entry', 'ورود'), ('exit', 'خروج')], max_length=10, verbose_name='نوع ورود/خروج')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='vehicle_entries/', verbose_name='تصویر ضبط شده')),
                ('plate_detection_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای تشخیص پلاک')),
                ('face_detection_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای تشخیص چهره')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_entries', to='parking.parkinglocation', verbose_name='پارکینگ')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_entries', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vehicles.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'ورود/خروج خودرو',
                'verbose_name_plural': 'ورود/خروج خودروها',
                'ordering': ['-timestamp'],
            },
        ),
    ]
