# Generated by Django 5.1.7 on 2025-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام داشبورد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('settings', models.JSONField(blank=True, null=True, verbose_name='تنظیمات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبوردها',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('widget_type', models.CharField(choices=[('chart', 'نمودار'), ('table', 'جدول'), ('metric', 'معیار'), ('map', 'نقشه'), ('custom', 'سفارشی')], default='chart', max_length=20, verbose_name='نوع ویجت')),
                ('category', models.CharField(choices=[('summary', 'خلاصه'), ('detailed', 'جزئیات'), ('analytics', 'تحلیلی')], default='summary', max_length=20, verbose_name='دسته\u200cبندی')),
                ('settings', models.JSONField(blank=True, null=True, verbose_name='تنظیمات')),
                ('position_x', models.IntegerField(default=0, verbose_name='موقعیت X')),
                ('position_y', models.IntegerField(default=0, verbose_name='موقعیت Y')),
                ('width', models.IntegerField(default=1, verbose_name='عرض')),
                ('height', models.IntegerField(default=1, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'ویجت داشبورد',
                'verbose_name_plural': 'ویجت\u200cهای داشبورد',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=10, verbose_name='report type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='status')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sessions', models.IntegerField(default=0)),
                ('average_session_duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زمان\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], default='monthly', max_length=20, verbose_name='تناوب')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='روز هفته')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='روز ماه')),
                ('time', models.TimeField(verbose_name='زمان اجرا')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=20, verbose_name='نوع گزارش')),
                ('category', models.CharField(choices=[('summary', 'خلاصه'), ('detailed', 'جزئیات'), ('analytics', 'تحلیلی')], default='summary', max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی گزارش',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای گزارش',
            },
        ),
    ]
