# Generated by Django 5.1.7 on 2025-03-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('items', models.JSONField(default=list, verbose_name='items')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('parking_session', 'Parking Session'), ('reservation', 'Reservation'), ('subscription', 'Subscription')], max_length=20, verbose_name='payment type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction ID')),
                ('payment_gateway', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment gateway')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment method')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درگاه')),
                ('gateway_type', models.CharField(choices=[('online', 'آنلاین'), ('pos', 'کارتخوان'), ('cash', 'نقدی'), ('wallet', 'کیف پول')], default='online', max_length=20, verbose_name='نوع درگاه')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='رمز API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='تنظیمات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10, verbose_name='subscription type')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10, verbose_name='period')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='auto renew')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_items', models.TextField()),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل (ریال)')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات')),
                ('tax_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ مالیات (ریال)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف (ریال)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='payments.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
